apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

nodeGroups:
  - name: nodegrp-1
    instanceType: t1.micro
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyName: ""
  - name: nodegrp-2
    instanceType: t1.micro
    desiredCapacity: 1
    ssh:
      allow: true
      publicKeyName: ""
 