version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building files
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no