apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
    - port: 3000
  selector:
    app: demo
    tier: frontend
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
    spec:
      containers:
      - image: CONTAINER_IMAGE
        name: demo
        ports:
        - containerPort: 3000
          name: demo
