apiVersion: v1
kind: Service
metadata:
  name: ebtf
  labels:
    app: ebtf
spec:
  ports:
    - port: 3000
  selector:
    app: ebtf
    tier: frontend
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ebtf
  labels:
    app: ebtf
spec:
  selector:
    matchLabels:
      app: ebtf
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ebtf
        tier: frontend
    spec:
      containers:
      - image: CONTAINER_IMAGE
        name: ebtf
        ports:
        - containerPort: 3000
          name: ebtf
